name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: cppwinrt
      cmakeInstallationPath: cppwinrt-installation
      tagName: 2.0.221121.5
      mingwTargetZip: cppwinrt-${{ github.ref_name }}-winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip
    steps:
      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/microsoft/cppwinrt.git # && cd cppwinrt && git checkout ${{ env.tagName }}
        
      - name: curl winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip
        shell: cmd
        run: |
          curl https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-12.0.1-9.0.0-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip -L --output winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip &&^
          7z.exe x winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip -o"C:\winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1\" &&^
          dir
          
      - name: curl cmake-3.22.2-windows-x86_64.zip
        shell: cmd
        run: |
          curl https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip -L --output cmake-3.22.2-windows-x86_64.zip &&^
          dir &&^
          7z.exe x cmake-3.22.2-windows-x86_64.zip
        
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
          set PATH=^
          C:\winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1;^
          C:\winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1\bin;^
          ${{ github.workspace }}\cmake-3.22.2-windows-x86_64\bin;
          gcc --version &&^
          set CD_LINUX=%CD:\=/%
          cd cppwinrt && ^
          cmake.exe -G "MinGW Makefiles" ^
          --toolchain cross-mingw-toolchain.cmake ^
          -DMINGW_BIN_PATH="C:/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1/bin" ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_INSTALL_PREFIX="cmake-build/${{ env.cmakeInstallationPath }}" ^
          -B./cmake-build &&^
          cd cmake-build &&^
          cmake --build . &&^
          cmake --install . 
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "cppwinrt/cmake-build/${{ env.cmakeInstallationPath }}"
          filename: "${{ env.mingwTargetZip }}"

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cppwinrt/cmake-build/${{ env.cmakeInstallationPath }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
